# Generated by Django 2.1.4 on 2018-12-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Films',
            new_name='Film',
        ),
    ]
