# Generated by Django 2.1.4 on 2018-12-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_screening'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('screening_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Screening')),
            ],
        ),
    ]
