# Generated by Django 2.1.4 on 2018-12-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='screening_id',
            new_name='screening',
        ),
    ]
