# Generated by Django 2.1.4 on 2018-12-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20181209_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='availability',
            new_name='available',
        ),
    ]
