# Generated by Django 2.1.4 on 2019-01-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancelled',
        ),
    ]
